# Conectar base de datos

In [2]:
import psycopg2

dbname = "NotesStudyTest"
user = "postgres"
password = "1234"
host = "localhost" 
port = "5432" 

# Establecer la conexión
try:
    connection = psycopg2.connect(
        dbname=dbname, user=user, password=password, host=host, port=port
    )
    print("Conexión exitosa a la base de datos")
except psycopg2.Error as e:
    print("Error al conectarse a la base de datos:", e)

Conexión exitosa a la base de datos

## Crear tablas relacionadas SQL

In [7]:
""" CREATE TABLE alumno (
    id_alumno    INTEGER NOT NULL,
    promedio     FLOAT,
    semestre     INTEGER,
    anio_entrada INTEGER,
    sexo         VARCHAR(10),
    edad         INTEGER
);

ALTER TABLE alumno ADD CONSTRAINT alumno_pk PRIMARY KEY ( id_alumno );

CREATE TABLE apoyoeconomico (
    id_alumno           INTEGER NOT NULL,
    localidad           VARCHAR(300),
    estrato             INTEGER,
    transporte          VARCHAR(100),
    personas_en_casa    INTEGER,
    apoyo_universitario VARCHAR(100),
    num_hijos           INTEGER,
    tiempo_transporte   INTEGER
);

CREATE TABLE asistencia (
    id_alumno             INTEGER NOT NULL,
    faltas_justificadas   INTEGER,
    faltas_injustificadas INTEGER
);

CREATE TABLE materia (
    id_materia     INTEGER NOT NULL,
    nombre_materia VARCHAR(255),
    creditos       VARCHAR(255),
    hora_inicio    VARCHAR(20),
    hora_fin       VARCHAR(20),
    dias           VARCHAR(255),
    profesor       INTEGER NOT NULL
);

ALTER TABLE materia ADD CONSTRAINT materia_pk PRIMARY KEY ( id_materia );

CREATE TABLE nota (
    id_materia          INTEGER NOT NULL,
    id_alumno           INTEGER NOT NULL,
    nota_final          FLOAT,
    grupo               VARCHAR(20),
    registro_asistencia INTEGER,
    horas_estudiadas    INTEGER
);

CREATE TABLE profesor (
    id_profesor          INTEGER NOT NULL,
    nombre_profesor      VARCHAR(255),
    semestre             INTEGER,
    grupo                VARCHAR(10),
    num_estudiantes      INTEGER,
    facultad             VARCHAR(100),
    titulo_universitario VARCHAR(200),
    id_materia           INTEGER
);

ALTER TABLE profesor ADD CONSTRAINT profesor_pk PRIMARY KEY ( id_profesor );

ALTER TABLE asistencia
    ADD CONSTRAINT asistencia_alumno_fk FOREIGN KEY ( id_alumno )
        REFERENCES alumno ( id_alumno );

ALTER TABLE materia
    ADD CONSTRAINT table_3_profesor_fk FOREIGN KEY ( profesor )
        REFERENCES profesor ( id_profesor );

ALTER TABLE apoyoeconomico
    ADD CONSTRAINT table_6_alumno_fk FOREIGN KEY ( id_alumno )
        REFERENCES alumno ( id_alumno );

ALTER TABLE nota
    ADD CONSTRAINT table_7_alumno_fk FOREIGN KEY ( id_alumno )
        REFERENCES alumno ( id_alumno );

ALTER TABLE nota
    ADD CONSTRAINT table_7_materia_fk FOREIGN KEY ( id_materia )
        REFERENCES materia ( id_materia );"""

' CREATE TABLE alumno (\n    id_alumno    INTEGER NOT NULL,\n    promedio     FLOAT,\n    semestre     INTEGER,\n    anio_entrada INTEGER,\n    sexo         VARCHAR(10),\n    edad         INTEGER\n);\n\nALTER TABLE alumno ADD CONSTRAINT alumno_pk PRIMARY KEY ( id_alumno );\n\nCREATE TABLE apoyoeconomico (\n    id_alumno           INTEGER NOT NULL,\n    localidad           VARCHAR(300),\n    estrato             INTEGER,\n    transporte          VARCHAR(100),\n    personas_en_casa    INTEGER,\n    apoyo_universitario VARCHAR(100),\n    num_hijos           INTEGER,\n    tiempo_transporte   INTEGER\n);\n\nCREATE TABLE asistencia (\n    id_alumno             INTEGER NOT NULL,\n    faltas_justificadas   INTEGER,\n    faltas_injustificadas INTEGER\n);\n\nCREATE TABLE materia (\n    id_materia     INTEGER NOT NULL,\n    nombre_materia VARCHAR(255),\n    creditos       VARCHAR(255),\n    hora_inicio    VARCHAR(20),\n    hora_fin       VARCHAR(20),\n    dias           VARCHAR(255),\n    profesor       INTEGER NOT NULL\n);\n\nALTER TABLE materia ADD CONSTRAINT materia_pk PRIMARY KEY ( id_materia );\n\nCREATE TABLE nota (\n    id_materia          INTEGER NOT NULL,\n    id_alumno           INTEGER NOT NULL,\n    nota_final          FLOAT,\n    grupo               VARCHAR(20),\n    registro_asistencia INTEGER,\n    horas_estudiadas    INTEGER\n);\n\nCREATE TABLE profesor (\n    id_profesor          INTEGER NOT NULL,\n    nombre_profesor      VARCHAR(255),\n    semestre             INTEGER,\n    grupo                VARCHAR(10),\n    num_estudiantes      INTEGER,\n    facultad             VARCHAR(100),\n    titulo_universitario VARCHAR(200),\n    id_materia           INTEGER\n);\n\nALTER TABLE profesor ADD CONSTRAINT profesor_pk PRIMARY KEY ( id_profesor );\n\nALTER TABLE asistencia\n    ADD CONSTRAINT asistencia_alumno_fk FOREIGN KEY ( id_alumno )\n        REFERENCES alumno ( id_alumno );\n\nALTER TABLE materia\n    ADD CONSTRAINT table_3_profesor_fk FOREIGN KEY ( profesor )\n        REFERENCES profesor ( id_profesor );\n\nALTER TABLE apoyoeconomico\n    ADD CONSTRAINT table_6_alumno_fk FOREIGN KEY ( id_alumno )\n        REFERENCES alumno ( id_alumno );\n\nALTER TABLE nota\n    ADD CONSTRAINT table_7_alumno_fk FOREIGN KEY ( id_alumno )\n        REFERENCES alumno ( id_alumno );\n\nALTER TABLE nota\n    ADD CONSTRAINT table_7_materia_fk FOREIGN KEY ( id_materia )\n        REFERENCES materia ( id_materia );'

## Test inicial

In [15]:
# Agregar valores de ejemplo a la base de datos
try:
    connection = psycopg2.connect(
        dbname=dbname, user=user, password=password, host=host, port=port
    )
    print("Conexión exitosa a la base de datos")

    # Agregar valores de prueba
    cursor = connection.cursor()
    cursor.execute("INSERT INTO alumno (id_alumno, promedio, semestre) VALUES (1, 85.0, 2)")
    connection.commit()
    print("Valores de prueba insertados correctamente")

    cursor.close()

except psycopg2.Error as e:
    print("Error al conectarse a la base de datos:", e)

Conexión exitosa a la base de datos
Valores de prueba insertados correctamente

In [16]:
try:
    connection = psycopg2.connect(
        dbname=dbname, user=user, password=password, host=host, port=port
    )
    print("Conexión exitosa a la base de datos")

    # Consulta para obtener los datos insertados
    consulta = "SELECT * FROM alumno"
    cursor = connection.cursor()
    cursor.execute(consulta)
    resultados = cursor.fetchall()

    # Imprimir los resultados
    for fila in resultados:
        print(fila)

    cursor.close()

except psycopg2.Error as e:
    print("Error al conectarse a la base de datos:", e)

Conexión exitosa a la base de datos
(1, 85.0, 2, None, None, None)

In [17]:
try:
    connection = psycopg2.connect(
        dbname=dbname, user=user, password=password, host=host, port=port
    )
    print("Conexión exitosa a la base de datos")

    # Consulta para eliminar los datos de prueba
    consulta = "DELETE FROM alumno WHERE id_alumno = 1"  
    cursor = connection.cursor()
    cursor.execute(consulta)
    connection.commit()
    print("Datos de prueba eliminados correctamente")

    cursor.close()

except psycopg2.Error as e:
    print("Error al conectarse a la base de datos:", e)

Conexión exitosa a la base de datos
Datos de prueba eliminados correctamente

# Agregar datos de prueba (INSERT 100 datos)

In [14]:
import psycopg2
from faker import Faker
import random
from datetime import datetime, time

dbname = "NotesStudyTest"
user = "postgres"
password = "1234"
host = "localhost"
port = "5432"

faker = Faker()

# Generar 100 datos de ejemplo para cada tabla
alumnos = [(i, faker.pyfloat(min_value=0, max_value=5), faker.random_int(min=1, max=8),
                faker.random_int(min=2000, max=2022), faker.random_element(["Masculino", "Femenino"]),
                faker.random_int(min=16, max=30)) for i in range(1, 101)]

apoyos = [(i, faker.city(), faker.random_int(min=1, max=6), faker.random_element(["Bus", "Trasmilenio", "Bicicleta","Carro","Moto","Taxi","Flota","Caminando","Ruta","Servicios de trasporte privados"]),
               faker.random_int(min=1, max=6), faker.random_element(["Sí", "No"]),
               faker.random_int(min=0, max=5), faker.random_int(min=5, max=120)) for i in range(1, 101)]

asistencias = [(i, faker.random_int(min=0, max=10), faker.random_int(min=0, max=5)) for i in range(1, 101)]

profesores = [(i, faker.name(), faker.random_int(min=1, max=10), faker.random_element(["A", "B", "C"]),
                   faker.random_int(min=10, max=40), faker.random_element(["Materia A", "Materia B", "Materia C","Materia D","Materia E","Materia F","Materia G","Materia H","Materia I","Materia J"]),
                   faker.job(), i) for i in range(1, 101)]

horarios = [time(random.randint(1, 10), random.randint(0, 59), 0) for _ in range(100)]

materias = [(i, faker.catch_phrase(), faker.random_int(min=1, max=4),
                     datetime.combine(datetime.today(), horarios[i - 1]).strftime('%I:%M%p'),
                     datetime.combine(datetime.today(), horarios[i - 1]).strftime('%I:%M%p'),
                     faker.random_element(["Lunes-Miércoles", "Martes-Jueves", "Viernes"]), i)
                    for i in range(1, 101)]

notas = [(i, i, random.uniform(0, 5), faker.random_element(["A", "B", "C"])
          , faker.random_int(min=0, max=10), faker.random_int(min=1, max=10)) for i in range(1, 101)]

try:
    connection = psycopg2.connect(
        dbname=dbname, user=user, password=password, host=host, port=port
    )
    print("Conexión exitosa a la base de datos")

    cursor = connection.cursor()


    # Insertar datos en las tablas
    cursor.executemany("INSERT INTO alumno VALUES (%s, %s, %s, %s, %s, %s)", alumnos)
    print("Alumnos insertados correctamente")
    cursor.executemany("INSERT INTO apoyoeconomico VALUES (%s, %s, %s, %s, %s, %s, %s, %s)", apoyos)
    print("Apoyos insertados correctamente")
    cursor.executemany("INSERT INTO asistencia VALUES (%s, %s, %s)", asistencias)
    print("Asistencias insertadas correctamente")
    cursor.executemany("INSERT INTO profesor VALUES (%s, %s, %s, %s, %s, %s, %s, %s)", profesores)
    print("Profesores insertados correctamente")
    cursor.executemany("INSERT INTO materia VALUES (%s, %s, %s, %s, %s, %s, %s)", materias)
    print("Materias insertadas correctamente")
    cursor.executemany("INSERT INTO nota VALUES (%s, %s, %s, %s, %s, %s)", notas)
    print("Notas insertadas correctamente")
    
    connection.commit()
    print("Datos de prueba insertados correctamente")

    cursor.close()

except psycopg2.Error as e:
    print("Error al conectarse a la base de datos:", e)

Conexión exitosa a la base de datos
Alumnos insertados correctamente
Apoyos insertados correctamente
Asistencias insertadas correctamente
Profesores insertados correctamente
Materias insertadas correctamente
Notas insertadas correctamente
Datos de prueba insertados correctamente

### Eliminar datos

In [12]:
import psycopg2

# Parámetros de conexión
dbname = "NotesStudyTest"
user = "postgres"
password = "1234"
host = "localhost"
port = "5432"

try:
    connection = psycopg2.connect(
        dbname=dbname, user=user, password=password, host=host, port=port
    )
    print("Conexión exitosa a la base de datos")

    cursor = connection.cursor()

    # Eliminar los datos anteriores
    cursor.execute("DELETE FROM nota")
    cursor.execute("DELETE FROM asistencia")
    cursor.execute("DELETE FROM apoyoeconomico")
    cursor.execute("DELETE FROM materia")
    cursor.execute("DELETE FROM profesor")
    cursor.execute("DELETE FROM alumno")

    connection.commit()
    print("Datos de prueba reemplazados correctamente")

    cursor.close()

except psycopg2.Error as e:
    print("Error al conectarse a la base de datos:", e)

Conexión exitosa a la base de datos
Datos de prueba reemplazados correctamente